# Generated by Django 5.0.1 on 2024-01-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscularGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
